apiVersion: argoproj.io/v1alpha1
kind: Workflow                  #new type of k8s spec
metadata:
  generateName: nlp-evaluate-wf-    #name of workflow spec
spec:
  entrypoint: nlp-eval          #invoke the build template
  volumes:
  - name: test-volume
    hostPath:
      path: /home/amia/tutorial
  
  templates:

  - name: nlp-eval
    steps:
    - - name: svm # run as parallel steps
        template: run-svm

      - name: log
        template: run-log

      - name: mlp 
        template: run-mlp

      - name: bag 
        template: run-bag
    
      - name: boost 
        template: run-boost
    
      - name: rf 
        template: run-rf
    
    - - name: ensemble # run as serial steps
        template: run-ensemble

    - - name: cnn 
        template: run-cnn
    
    - - name: vote 
        template: run-vote
  
  - name: run-svm
    container:
      image: nlpieumn/ml
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./ml.py"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-log
    container:
      image: nlpieumn/ml
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./ml.py -c log"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-mlp
    container:
      image: nlpieumn/ml
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./ml.py -c mlp"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-rf
    container:
      image: nlpieumn/ml
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./ml.py -c rf"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-bag
    container:
      image: nlpieumn/ml
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./ml.py -c bag"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
  
  - name: run-boost
    container:
      image: nlpieumn/ml
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./ml.py -c boost"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false

  - name: run-ensemble
    container:
      image: nlpieumn/ml
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./ensemble.py"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
  
  - name: run-cnn
    container:
      image: nlpieumn/cnn
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["PYTHONHASHSEED=0 python ./cnn.py"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
  
  - name: run-vote
    container:
      image: nlpieumn/vote
      imagePullPolicy: Never
      env:
        - name: DOCKER         
          value: "True"
      command: [sh, -c]
      args: ["python ./vote.py"] 
      volumeMounts:
      - name: test-volume
        mountPath: /data
        readOnly: false
